---
# Role tasks

- name: Configure SELinux
  ansible.posix.selinux:
    state: "{{ selinux_mode }}"
    policy: "{{ selinux_policy }}"
  when: selinux_mode != "unchanged"
  notify:
    - reboot host
    - wait host
  tags:
    - role::selinux
