---
# Role tasks

- name: install selinux
  include_tasks: install.yml
  tags:
    - role::selinux
    - role::selinux::install

- name: configure selinux
  include_tasks: configure.yml
  tags:
    - role::selinux
    - role::selinux::configure
