---
# Role tasks

- name: install selinux packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ selinux_packages[ansible_distribution | lower] }}"
  tags:
    - role::selinux
    - role::selinux::packages

- block:

  - name: setup selinux
    selinux:
      state: "{{ selinux_config.mode }}"
      policy: "{{ selinux_config.policy }}"
    notify:
      - reboot
      - wait

  - meta: flush_handlers

  tags:
    - role::selinux
    - role::selinux::configure
