---
# Role tasks

- name: install selinux
  include: install.yml
  static: false
  tags:
    - role::selinux
    - role::selinux::install

- name: configure selinux
  include: configure.yml
  static: false
  tags:
    - role::selinux
    - role::selinux::configure
