---
# Role handlers

- name: reboot
  command: shutdown -r +1 'Ansible selinux role triggered a reboot'
  changed_when: true
  async: 0
  poll: 0
  ignore_errors: true

- name: wait
  wait_for:
    host: "{{ inventory_hostname }}"
    state: started
    port: "{{ selinux_config.wait_port | default(ansible_port) | default(22) }}"
    delay: 10
    timeout: "{{ selinux_config.wait_timeout | default(300) }}"
  delegate_to: localhost
